"""Exact finite witnesses and chart diagnostics for finite-two-sample-minimum."""
from fractions import Fraction as F


def minimum_score(law):
    assert sum(law.values(), F(0)) == 1
    return sum(
        (px * py * min(x, y) for x, px in law.items() for y, py in law.items()),
        F(0),
    )


def mix(p, left, right):
    law = {}
    for weight, branch in ((p, left), (1 - p, right)):
        for x, probability in branch.items():
            law[x] = law.get(x, F(0)) + weight * probability
    return law


def sure(x):
    return {F(x): F(1)}


def chart_outcome(r):
    return r * r if r >= 0 else -(r * r) / (1 - 2 * r)


def main():
    # Every tested level uses the relevant normalized binary comparison,
    # with raw outcomes generated by the proposed inverse chart.
    levels = [F(-5), F(-2), F(-1), F(-1, 2), F(0), F(1, 4), F(1, 2), F(1), F(2), F(3)]
    for r in levels:
        x = chart_outcome(r)
        if 0 <= r <= 1:
            assert minimum_score(mix(r, sure(1), sure(0))) == x
        elif r > 1:
            assert minimum_score(mix(1 / r, sure(x), sure(0))) == 1
        else:
            assert minimum_score(mix(-r / (1 - r), sure(1), sure(x))) == 0
    assert all(chart_outcome(a) < chart_outcome(b) for a, b in zip(levels, levels[1:]))

    # Equal expectations in the uniquely calibrated chart, unequal scores.
    x_law = mix(F(1, 2), sure(chart_outcome(F(2))), sure(chart_outcome(F(1))))
    y_law = sure(chart_outcome(F(3, 2)))
    assert F(1, 2) * 2 + F(1, 2) * 1 == F(3, 2)
    assert minimum_score(x_law) == F(7, 4)
    assert minimum_score(y_law) == F(9, 4)

    # An indifferent pair is separated by a common mixture with sure 1.
    lottery = mix(F(1, 2), sure(4), sure(0))
    assert minimum_score(lottery) == minimum_score(sure(1)) == 1
    assert minimum_score(mix(F(1, 2), lottery, sure(1))) == F(3, 4)
    assert minimum_score(mix(F(1, 2), sure(1), sure(1))) == 1

    # Binary scores reach intermediate sure levels on both sides of zero.
    for a, c in ((F(4), F(1)), (F(2), F(-3)), (F(-1), F(-5))):
        for p in (F(1, 4), F(1, 2), F(3, 4)):
            b = c + (a - c) * p * p
            assert c < b < a
            assert minimum_score(mix(p, sure(a), sure(c))) == b
    print('PASS: exact chart calibrations, Simple EU counterexample, mixture-independence failure, and binary intermediate values')


if __name__ == '__main__':
    main()
